/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yanhan_com_mycalljava_JNI */

#ifndef _Included_yanhan_com_mycalljava_JNI
#define _Included_yanhan_com_mycalljava_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yanhan_com_mycalljava_JNI
 * Method:    callbackadd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yanhan_com_mycalljava_JNI_callbackadd
  (JNIEnv *, jobject);

/*
 * Class:     yanhan_com_mycalljava_JNI
 * Method:    callbackFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yanhan_com_mycalljava_JNI_callbackFromJava
  (JNIEnv *, jobject);

/*
 * Class:     yanhan_com_mycalljava_JNI
 * Method:    callbackprintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yanhan_com_mycalljava_JNI_callbackprintString
  (JNIEnv *, jobject);

/*
 * Class:     yanhan_com_mycalljava_JNI
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yanhan_com_mycalljava_JNI_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
