/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yanhan_com_ndkdemo_JNI */

#ifndef _Included_yanhan_com_ndkdemo_JNI
#define _Included_yanhan_com_ndkdemo_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yanhan_com_ndkdemo_JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_yanhan_com_ndkdemo_JNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     yanhan_com_ndkdemo_JNI
 * Method:    sayhello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yanhan_com_ndkdemo_JNI_sayhello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     yanhan_com_ndkdemo_JNI
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_yanhan_com_ndkdemo_JNI_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     yanhan_com_ndkdemo_JNI
 * Method:    checkpwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_yanhan_com_ndkdemo_JNI_checkpwd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
